name: authentication_app
description: Simple Flutter app with a user authentication flow using Firebase Authentication and FirebaseUI.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  flutterfire_ui: ^0.4.3+20
  google_sign_in: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
