// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE1oybv2ZGccQ0lPz5kTT0tHC9ujUf9EU',
    appId: '1:763884961458:web:bb6d563eff2b8a61bbd3ab',
    messagingSenderId: '763884961458',
    projectId: 'authentication-app-d771b',
    authDomain: 'authentication-app-d771b.firebaseapp.com',
    storageBucket: 'authentication-app-d771b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsqRY_SRFiR1a91omjpszdqU_CaRoi2mA',
    appId: '1:763884961458:android:5dfbb508d052cb4dbbd3ab',
    messagingSenderId: '763884961458',
    projectId: 'authentication-app-d771b',
    storageBucket: 'authentication-app-d771b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXkXqlmv3YW_RAIiU5eSEjkAyj_9G80so',
    appId: '1:763884961458:ios:a9c0669c8f941345bbd3ab',
    messagingSenderId: '763884961458',
    projectId: 'authentication-app-d771b',
    storageBucket: 'authentication-app-d771b.appspot.com',
    iosClientId: '763884961458-u3j2lr4339k9p6eg8kj5odt8etqm930d.apps.googleusercontent.com',
    iosBundleId: 'com.authentication.app.authenticationApp',
  );
}
